import Navbar from './navbar';
import '../../styles/tailwind.css';
import '../../styles/main.scss';
export const metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
	return (
		<html lang="en">
			<body>
				<Navbar />
				<div className="container mx-auto">{children}</div>
			</body>
		</html>
	);
}
